import os
from shutil import copyfile
from glob import glob
import argparse

#read/write excel
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
#Misc. utilities
from Misc_Utils import get_date
#creating canvas to draw pdf
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, A4
from Draw_Utils import draw_invoice_template, draw_service, draw_end

parser = argparse.ArgumentParser()
parser.add_argument('--month', type=int, default=0)
parser.add_argument('--year', type=int, default=0)

opt = parser.parse_args()

TPS_rate = 0.05
TVQ_rate = 0.09975

day, month, month_num, year = get_date(opt.month, opt.year)


#ClientRevenueReportList.xlsx is generated by GoRendezVous
#OverviewSheet is maintained by Bianca, contains data about each therapists payment schemes
month_data = pd.read_excel('ClientRevenueReportList.xlsx', sheet_name='Sheet1')
therapist_data = pd.read_excel('OverviewSheet.xlsx', sheet_name="Sheet1")

if not os.path.exists("_Recent"):
		os.makedirs("_Recent")
files = glob('_Recent/*')
for f in files:
	os.remove(f)

for i in therapist_data.index:
	therapist = str(therapist_data['Name'][i])
	pays_tax = True if therapist_data['Pays Tax'][i] == "Y" else False
	first_percentage = float(therapist_data['First Appointment Percentage'][i])
	follow_percentage = float(therapist_data['Follow Up Percentage'][i])

	if not os.path.exists(therapist):
		os.makedirs(therapist)
	if not os.path.exists(therapist + os.sep + year):
		os.makedirs(therapist + os.sep + year)

	#print("Name: {}, Pays Tax:{}, First Appointment:{}, Follow Up Appointment:{}".format(therapist,pays_tax,first_percentage,follow_percentage))

	filename = therapist + os.sep + year + os.sep + therapist + "_facture_" + month + "_" + year + ".pdf"
	invoice = canvas.Canvas(filename , pagesize=A4)
	position = draw_invoice_template(invoice, therapist, year, str(month_num).zfill(2), str(day).zfill(2))

	partial = 0.0
	for j in month_data.index:
		if str(month_data['Professional'][j]) == therapist:
			service = month_data['Service'][j].strip()
			price = month_data['Price'][j]
			quantity = month_data['Quantity'][j]
			revenue = month_data['Revenue'][j]
			# balance = str(month_data['Balance'][j])
			if ("Premier" in service):
				position = draw_service(invoice, position, service, str(first_percentage), revenue, revenue * first_percentage, quantity)
				partial += revenue * first_percentage
			elif ("Suivi" in service):
				position = draw_service(invoice, position, service, str(follow_percentage), revenue, revenue * follow_percentage, quantity)
				partial += revenue * follow_percentage
			else:
				position = draw_service(invoice, position, service, "-", revenue, 0, quantity)

	total = 0.0
	TPS_total = partial * TPS_rate
	TVQ_total = partial * TVQ_rate
	if pays_tax:
		total = partial + TPS_total + TVQ_total
	else:
		total = partial

	draw_end(invoice, position, partial, TPS_total, TVQ_total, total, pays_tax)
	invoice.showPage()
	invoice.save()

	#Copy last created invoices into _Recent/ directory
	copyfile(filename, "_Recent" + os.sep + therapist + "_facture_" + month + "_" + year + ".pdf")
print("Invoices Created")

